In [1]:
import pandas as pd
import numpy as np

In [2]:
movies=pd.read_csv("data/tmdb-movies.csv")

In [3]:
movies.head(1)

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/15,5562,6.5,2015,1.379999e+08,1.392446e+09

In [4]:
m1=movies[["id","original_title","cast","director","overview","genres"]]

In [5]:
m1.isnull().sum()

id                 0
original_title     0
cast              76
director          44
overview           4
genres            23
dtype: int64

In [6]:
m1.dropna(inplace=True)

C:\Users\malay\AppData\Local\Temp\ipykernel_8060\3869780105.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m1.dropna(inplace=True)

In [7]:
m1.duplicated().sum()

1

In [8]:
m1.shape

(10730, 6)

In [9]:
m1.drop_duplicates(keep="first",inplace=True)

C:\Users\malay\AppData\Local\Temp\ipykernel_8060\2830841187.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m1.drop_duplicates(keep="first",inplace=True)

In [10]:
m1

,id,original_title,cast,director,overview,genres
0,135397,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,Twenty-two years after the events of Jurassic ...,Action|Adventure|Science Fiction|Thriller
1,76341,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,An apocalyptic story set in the furthest reach...,Action|Adventure|Science Fiction|Thriller
2,262500,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,Beatrice Prior must confront her inner demons ...,Adventure|Science Fiction|Thriller
3,140607,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Thirty years after defeating the Galactic Empi...,Action|Adventure|Science Fiction|Fantasy
4,168259,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Deckard Shaw seeks revenge against Dominic Tor...,Action|Crime|Thriller
...,...,...,...,...,...,...
10861,21,The Endless Summer,Michael Hynson|Robert August|Lord 'Tally Ho' B...,Bruce Brown,"The Endless Summer, by Bruce Brown, is one of ...",Documentary
10862,20379,Grand Prix,James Garner|Eva Marie Saint|Yves Montand|Tosh...,John Frankenheimer,Grand Prix driver Pete Aron is fired by his te...,Action|Adventure|Drama
10863,39768,Beregis Avtomobilya,Innokentiy Smoktunovskiy|Oleg Efremov|Georgi Z...,Eldar Ryazanov,An insurance agent who moonlights as a carthie...,Mystery|Comedy
10864,21449,"What's Up, Tiger Lily?",Tatsuya Mihashi|Akiko Wakabayashi|Mie Hama|Joh...,Woody Allen,"In comic Woody Allen's film debut, he took the...",Action|Comedy
10865,22293,Manos: The Hands of Fate,Harold P. Warren|Tom Neyman|John Reynolds|Dian...,Harold P. Warren,A family gets lost on the road and stumbles up...,Horror

In [11]:
m1["cast"][1]

'Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nicholas Hoult|Josh Helman'

In [12]:
m1["cast"]=m1["cast"].apply(lambda x:x.replace(" ",""))
m1["cast"]=m1["cast"].apply(lambda x:x.replace("|"," "))

C:\Users\malay\AppData\Local\Temp\ipykernel_8060\4013124952.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m1["cast"]=m1["cast"].apply(lambda x:x.replace(" ",""))
C:\Users\malay\AppData\Local\Temp\ipykernel_8060\4013124952.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m1["cast"]=m1["cast"].apply(lambda x:x.replace("|"," "))

In [13]:
#m1["cast"]=m1["cast"].apply(lambda x:x.replace(" ",""))
m1["genres"]=m1["genres"].apply(lambda x:x.replace("|"," "))

C:\Users\malay\AppData\Local\Temp\ipykernel_8060\470865462.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m1["genres"]=m1["genres"].apply(lambda x:x.replace("|"," "))

In [14]:
m1["director"]=m1["director"].apply(lambda x:x.replace(" ",""))

C:\Users\malay\AppData\Local\Temp\ipykernel_8060\1468225354.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m1["director"]=m1["director"].apply(lambda x:x.replace(" ",""))

In [15]:
m1

,id,original_title,cast,director,overview,genres
0,135397,Jurassic World,ChrisPratt BryceDallasHoward IrrfanKhan Vincen...,ColinTrevorrow,Twenty-two years after the events of Jurassic ...,Action Adventure Science Fiction Thriller
1,76341,Mad Max: Fury Road,TomHardy CharlizeTheron HughKeays-Byrne Nichol...,GeorgeMiller,An apocalyptic story set in the furthest reach...,Action Adventure Science Fiction Thriller
2,262500,Insurgent,ShaileneWoodley TheoJames KateWinslet AnselElg...,RobertSchwentke,Beatrice Prior must confront her inner demons ...,Adventure Science Fiction Thriller
3,140607,Star Wars: The Force Awakens,HarrisonFord MarkHamill CarrieFisher AdamDrive...,J.J.Abrams,Thirty years after defeating the Galactic Empi...,Action Adventure Science Fiction Fantasy
4,168259,Furious 7,VinDiesel PaulWalker JasonStatham MichelleRodr...,JamesWan,Deckard Shaw seeks revenge against Dominic Tor...,Action Crime Thriller
...,...,...,...,...,...,...
10861,21,The Endless Summer,MichaelHynson RobertAugust Lord'TallyHo'Blears...,BruceBrown,"The Endless Summer, by Bruce Brown, is one of ...",Documentary
10862,20379,Grand Prix,JamesGarner EvaMarieSaint YvesMontand ToshirÅM...,JohnFrankenheimer,Grand Prix driver Pete Aron is fired by his te...,Action Adventure Drama
10863,39768,Beregis Avtomobilya,InnokentiySmoktunovskiy OlegEfremov GeorgiZhzh...,EldarRyazanov,An insurance agent who moonlights as a carthie...,Mystery Comedy
10864,21449,"What's Up, Tiger Lily?",TatsuyaMihashi AkikoWakabayashi MieHama JohnSe...,WoodyAllen,"In comic Woody Allen's film debut, he took the...",Action Comedy
10865,22293,Manos: The Hands of Fate,HaroldP.Warren TomNeyman JohnReynolds DianeMah...,HaroldP.Warren,A family gets lost on the road and stumbles up...,Horror

In [16]:
m1["tags"]=m1["overview"]+m1["genres"]+m1["cast"]+m1["director"]

C:\Users\malay\AppData\Local\Temp\ipykernel_8060\3251833730.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m1["tags"]=m1["overview"]+m1["genres"]+m1["cast"]+m1["director"]

In [17]:
m1["tags"]=m1["tags"].apply(lambda x:x.lower())

C:\Users\malay\AppData\Local\Temp\ipykernel_8060\2765953529.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m1["tags"]=m1["tags"].apply(lambda x:x.lower())

In [18]:
m2=m1[["id","original_title","tags"]]

In [19]:
m2.head(3)

,id,original_title,tags
0,135397,Jurassic World,twenty-two years after the events of jurassic ...
1,76341,Mad Max: Fury Road,an apocalyptic story set in the furthest reach...
2,262500,Insurgent,beatrice prior must confront her inner demons ...

In [20]:
m2.shape

(10729, 3)

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
cv=CountVectorizer(max_features=9000,stop_words="english")

In [28]:
vectors=cv.fit_transform(m2["tags"]).toarray()

In [29]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
import nltk

In [22]:
from nltk.stem.porter import PorterStemmer

In [23]:
ps=PorterStemmer()

In [24]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [25]:
m2["tags"]=m2["tags"].apply(stem)

C:\Users\malay\AppData\Local\Temp\ipykernel_8060\3000943900.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m2["tags"]=m2["tags"].apply(stem)

In [30]:
from sklearn.metrics.pairwise import cosine_similarity

In [31]:
similarity=cosine_similarity(vectors)

In [32]:
similarity[120]

array([0.        , 0.15467961, 0.        , ..., 0.10400629, 0.06933752,
       0.        ])

In [33]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(10061, 0.360555127546399),
 (10092, 0.35082320772281167),
 (5300, 0.3328751429678414),
 (5593, 0.2699527623995085),
 (1176, 0.2360960823249428)]

In [34]:
def recommend(movie):
    movie_index=m2[m2["original_title"]==movie].index[0]
    distances=similarity[movie_index]
    movie_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movie_list:
        print(m2["original_title"][i[0]])

In [35]:
recommend("Inside Out")

Riley's First Date?
Spider-Man 2
The House on Pine Street
Airport '77
Changeling

In [36]:
m2.head(10)

,id,original_title,tags
0,135397,Jurassic World,twenty-two year after the event of jurass park...
1,76341,Mad Max: Fury Road,an apocalypt stori set in the furthest reach o...
2,262500,Insurgent,beatric prior must confront her inner demon an...
3,140607,Star Wars: The Force Awakens,"thirti year after defeat the galact empire, ha..."
4,168259,Furious 7,deckard shaw seek reveng against domin toretto...
5,281957,The Revenant,"in the 1820s, a frontiersman, hugh glass, set ..."
6,87101,Terminator Genisys,"the year is 2029. john connor, leader of the r..."
7,286217,The Martian,"dure a man mission to mars, astronaut mark wat..."
8,211672,Minions,"minion stuart, kevin and bob are recruit by sc..."
9,150540,Inside Out,"grow up can be a bumpi road, and it' no except..."

In [37]:
import pickle

In [38]:
pickle.dump(m2,open("movies.pkl","wb"))

In [39]:
pickle.dump(similarity,open("similarity.pkl","wb"))

In [48]:
238 in m2["id"].values

True